version: "3.9"
name: openf1-strategy


services:
  # -------------------------------
  # Kafka broker (Redpanda)
  # -------------------------------
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    command: >
      redpanda start
      --overprovisioned
      --smp 1
      --memory 1G
      --reserve-memory 0M
      --node-id 0
      --check=false
      --kafka-addr PLAINTEXT://0.0.0.0:9092
      --advertise-kafka-addr PLAINTEXT://redpanda:9092
      --rpc-addr 0.0.0.0:33145
      --advertise-rpc-addr redpanda:33145
    ports:
      - "9092:9092"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  # -------------------------------
  # Replay service (Phase 1 ingestion)
  # -------------------------------
  replay:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: replay
    command: python -m ingest.replay
    environment:
      - KAFKA_BOOTSTRAP=redpanda:9092
      - TOPIC=telemetry.raw
    depends_on:
      - redpanda

  # -------------------------------
  # Strategy Engine (Phase 3)
  # -------------------------------
  engine:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: engine
    command: python -m engine.run
    environment:
      - KAFKA_BOOTSTRAP=redpanda:9092
      - TOPIC_IN=telemetry.raw
      - TOPIC_OUT=strategy.options
    depends_on:
      - redpanda
      - replay

  # -------------------------------
  # API (Phase 4 FastAPI)
  # -------------------------------
  api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: api
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    environment:
      - KAFKA_BOOTSTRAP=redpanda:9092
      - TOPIC_STRATEGY=strategy.options
    ports:
      - "8000:8000"
    depends_on:
      - redpanda
      - engine
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  # -------------------------------
  # Frontend (Phase 5 React)
  # -------------------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - api
